### ISSUE TITLE
Explore new features

### ISSUE THREAD

**Issue by baetheus** [baetheus/datum#3]
## Try adding metadata to pending types

```typescript
type Initial<M> = { _tag: 'Initial', meta: M };
type Pending<M> = { _tag: 'Pending', meta: M };
type Replete<V, M> = { _tag: 'Replete', value: V, meta: M };
type Refresh<V, M> = { _tag: 'Refresh', value: V, meta: M };

type DatumWithMeta<V, M = unknown> = Initial<M> | Pending<M> | Replete<V, M> | Refresh<V, M>;

type SomeData = { data: number[], nextUrl: string };

const datum: DatumWithMeta<SomeData, number> = { _tag: 'Initial', meta: 0 };
```

This is meant as an alternative to the web application case where slow incoming data with progress events has some tracked progress data:

```typescript
type ProgressDatum<V> = {
  datum: Datum<V>,
  progress: number,
};
```

The point of the exploration is to determine if there is another pattern lurking that can pull metadata along with it.

## Transform Datum with These in addition to Either

Something in particular to look at is [These](https://github.com/gcanti/fp-ts/blob/master/src/These.ts). Sometimes it is the case that error data needs to be preserved alongside return data.

**Comment by baetheus** [comment]
For the adding metadata exploration it's possible to also follow the example of These and treat DatumWithMeta as a bifunctor. In this case creating a similar getMonad factory that takes a semigroup to handle metadata merging would likely be enough to complete implementation. It's also possible to extend the existing Datum implementation with the default type value for M set to never/undefined in order to implement the existing Monad. Not sure if this is folly, though..

**Comment by smaccoun** [comment]
Do you think as a first step an optional progress could be added to `Pending`?

Something roughly like:
```
export interface Pending {
  readonly _tag: 'Pending'
  readonly progress: Option<{loaded: number, total: number}>
}
```

**Comment by baetheus** [comment]
@smaccoun That pattern is similar to the one in [remote-data-ts](https://github.com/devexperts/remote-data-ts/blob/master/src/remote-data.ts#L32). I have two problems with it:

First, it makes assumptions about how the nature of the underlying data. For example, loading information might not be numeric and might not have a concept of total and loaded. For example, say you were using DatumEither to represent discrete steps in a wizard process. You might want the pending state to be `{ currentStep: Option<1 | 2 | 3>; stepOneData: Option<string>; stepTwoData: Option<number>; stepThreeData: Option<boolean> }`. I'd like to handle this case with the abstraction I come up with.

Second, any optional progress would also need to be added to Refresh as well. On its face this isn't an issue, but it starts to become problematic when traversing, since it means new logic will have to be introduced to concat the four underlying types of Datum. This is why I think the secondary type should require a semigroup instance to function.

Probably a combination of your approach using Option with a new type could be useful. Ultimately, I don't think I should change the shape of Datum or DatumEither. Instead, I should probably look at creating a standalone type called something like `type Progress<T> = { _tag: "Progress", value: T }` that requires an semigroup for combining progress values. Then I can create a getDatumEitherM and use the existing getDatumM to create another set of ADTs ProgressDatum and ProgressDatumEither. Since we want a default value for T it's probable that I'll also want to implement (or require) an Alternative instance for Progress, since all Progress needs a concept of zero, or a place to start.

Anyway, I probably won't have time to work on this for awhile but if you want to take a crack at it I am open to PRs!
